### ISSUE TITLE
Pls can you share example code using this library to get multiple documents from qldb, can't find many examples of using qldb with golang

### ISSUE THREAD

**Issue by paragparandkar** [awslabs/amazon-qldb-driver-go#114]
Pls can you share example code using this library to get multiple documents from qldb, can't find many examples of using qldb with golang

**Comment by allimn** [comment]
https://docs.aws.amazon.com/qldb/latest/developerguide/driver-cookbook-golang.html

**Comment by bwinchester** [comment]
Did the developer guide help out? I will close this issue in 24 hours without further comment.
