### ISSUE TITLE
Correct the dates in CHANGELOG.md

### ISSUE THREAD

**Issue by yohanmartin** [awslabs/amazon-qldb-driver-go#29]
The `CHANGELOG` file at tag `v1.0.0` incorrectly mentions the dates of `v1.0.0` release as `2020-11-20` instead of `2020-10-20` and `v1.0.0-rc.1` as `2020-11-06` instead of `2020-10-06`.  The dates are updated in master though.

**Comment by aurghob33** [comment]
This change was merged in. Resolving the issue.
