### ISSUE TITLE
Log Level Unavailable

### ISSUE THREAD

**Issue by mousedownmike** [awslabs/amazon-qldb-driver-go#42]
The LogLevel used by the driver is never exposed through the interface and is therefore unavailable to anyone attempting to implement a custom logger.

The [AWS X-Ray SDK has a nice interface](https://github.com/aws/aws-xray-sdk-go/blob/master/xraylog/xray_log.go#L22) that was easy to customize.

```Go
type Logger interface {
	Log(level LogLevel, msg fmt.Stringer)
}
type LogLevel int

const (
	LogLevelDebug LogLevel = iota + 1
	LogLevelInfo
	LogLevelWarn
	LogLevelError
)
```

Would something similar (or even identical?) be acceptable?

**Comment by yoroto** [comment]
Thank you for raising it! We will get back to you asap.

**Comment by simonz-bq** [comment]
Hi @mousedownmike ,

The logging verbosity used by the driver is exposed as LogLevel, but not meant to be passed to the custom logger that you implement. The LogLevel can be set as a part of DriverOptions.LoggingVerbosity when creating a QLDBDriver as a functional parameter. The Driver then handles what to send to the logger given the LogLevel. 

[Please refer to Step 3 of the Go Driver QuickStart Guide for an example.](https://docs.aws.amazon.com/qldb/latest/developerguide/driver-quickstart-golang.html#driver-quickstart-golang.initialize)

If this does not provide the functionality that you desire, could you clarify what you're trying to do?

**Comment by mousedownmike** [comment]
@simonz-bq 

Log Level is important beyond just setting the verbosity of the logs, it is important metadata that is frequently used to set up alarms and log filters in tools like CloudWatch.  I use the `github.com/rs/zerolog/log` package to output structured logs that I can then use in CloudWatch.  An example of a recent X-Ray log output in CloudWatch is:

` {"level":"error","time":"2021-02-23T15:22:57Z","message":"write udp 169.254.79.1:54712->169.254.79.2:2000: write: connection refused"}`

By having this as structured output I'm able to extract `error` level messages across all my logs, generate reports, trigger alarms, etc... using the same metric.

If I want to use my logging mechanism, I would get something like the following from the QLDB driver:

`{"level":"info","time":"2021-02-23T15:22:57Z","message":"[DEBUG] Some debug statement"}`

There's a disconnect between the logging level the logger is using and the level the driver is using.  I think it's fine to be able to set the verbosity level directly with the driver but I would like the level of each log message to be a part of the log metadata so it can be used for monitoring.  It would be my pattern to set the logging level of the driver to be "one above debug" and then control the remaining levels with my logger.  I know you only have INFO and DEBUG now but I imagine that could change in the future.

As I mentioned in #38, it would be nice if there were more consistency among the AWS packages.  In this case, I think the logger from the `aws-xray-sdk-go` package provides a nice pattern.  At present, I have the following adapter that I use for X-Ray.  If I could reuse this across multiple AWS products, it would help reduce the "undifferentiated heavy lifting"  involved with integrating these sevices:

```Go
/*
XrayZerologAdapter is passed to AWS X-Ray to have service logs use zerolog
*/
type XrayZerologAdapter struct {
	MaxLevel xraylog.LogLevel
}

/*
Log calls the appropriate zerolog log function based on xraylog.LogLevel and
uses the supplied fmt.Stringer's String() method to generate the log message.
*/
func (x *XrayZerologAdapter) Log(ll xraylog.LogLevel, msg fmt.Stringer) {
	if ll >= x.MaxLevel {
		switch ll {
		case xraylog.LogLevelDebug:
			log.Debug().Msg(msg.String())
		case xraylog.LogLevelInfo:
			log.Info().Msg(msg.String())
		case xraylog.LogLevelWarn:
			log.Warn().Msg(msg.String())
		case xraylog.LogLevelError:
			log.Error().Msg(msg.String())
		}
	}
}
```

Please let me know if I can clarify this further.

**Comment by simonz-bq** [comment]
@mousedownmike 

Thank you for the explanation and the example of what functionality you wished to implement. It's now clear why you want to have access to the logging metadata. 

We will investigate this and decide how to implement this in the driver and make it available to you. We will take into consideration how the AWS X-Ray SDK does this for our design.
