### ISSUE TITLE
Support for aws-go-sdk-v2

### ISSUE THREAD

**Issue by errorhandler** [awslabs/amazon-qldb-driver-go#45]
Now that the V2 SDK is GA, we're using the V2 SDK for interacting with other AWS services. Having both SDK versions in our code base can make imports quite confusing. Is there any plans to switch to the V2 SDK for the low level API?

**Comment by simonz-bq** [comment]
Hi @errorhandler,

We're eventually planning on doing this but don't have a concrete date for it yet. It's a breaking change that requires a major version bump so we're holding off on it while we explore other potential breaking improvements we can bundle in with the release.

**Comment by plaucorp** [comment]
any news, I saw a major version bump some days ago and no support for aws-go-sdk-v2

**Comment by alpian** [comment]
Hi @plaucorp, I’m sorry it was confusing to bump the major version without support for the v2 SDK. We had backwards-breaking changes to release for the past few months and decided to ship them as soon as we could. I will come back on this thread with an update on when we can expect the v2 SDK support as possible.

**Comment by sonufrienko** [comment]
Any news here?
We start using QLDB and really need SDK v2 support.

**Comment by DanielBauman88** [comment]
Any update on this - is there an expectation of when v2 support will be released?

**Comment by butleragrant** [comment]
We have released a new version of the Go driver, which has SDK v2 support.
