### ISSUE TITLE
Wrapped error retry

### ISSUE THREAD

**Issue by errorhandler** [awslabs/amazon-qldb-driver-go#46]
As far as I understand it, the QLDB driver takes the error returned by the user-provided transaction function and [sees if the error is an AWS request failure, and determines if the request should be retried and other details based on the type.](https://github.com/awslabs/amazon-qldb-driver-go/blob/master/qldbdriver/session.go#L57)
```go
	if awsErr, ok := err.(awserr.RequestFailure); ok {
```

However, this requires the transaction function to return any errors from calls to the Transaction type verbatim for any retry logic to work.

I found this out when returning a wrapped error from the transaction function:
```go
	err := txn.Execute(....)
	if err != nil {
		return nil, fmt.Errorf("....: %w", err)
	}
```

To resolve this it would be great if the check used error unwrapping so that retries still worked when wrapping the raw AWS error.

**Comment by simonz-bq** [comment]
@errorhandler 

Can you describe the use case a little bit more? My understanding of what you're doing may be off the mark so correct me if it's wrong. We encourage people to return the error as is. If we used error unwrapping that may cause issues with people who don't wrap their errors as you have and we'd run into the same issue but with a different set of users.

Going off your code snippet, we'd recommend the optimal usage to be
```
res, err := driver.Execute(context.Background(), func(txn qldbdriver.Transaction) (interface{}, error) {
    result, err := txn.Execute(....)
    if err != nil {
	return nil, err
    }
    return result
})
if err != nil {
    err = fmt.Errorf("....: %w", err)
    //  Do whatever else
}
```

**Comment by errorhandler** [comment]
We use error wrapping to provide a "stack trace" of sorts to know _what_ caused the error to aid debugging.

We're currently returning a wrapped error to denote which step of the transaction caused an issue, in cases where there are multiple error exit points.

My understanding may be incorrect but using [`errors.As`](https://golang.org/pkg/errors/#As) wouldn't break existing error usage as it does check if the error is assignable to the target errors, as the driver does now:

>An error matches target if the error's concrete value is assignable to the value pointed to by target, or if the error has a method As(interface{}) bool such that As(target) returns true. In the latter case, the As method is responsible for setting target.

**Comment by justing-bq** [comment]
@errorhandler We have resolved your issue and it will be in our next release.

**Comment by errorhandler** [comment]
> @errorhandler We have resolved your issue and it will be in our next release.

Legend! Thanks so much!

**Comment by byronlin13** [comment]
Hi @errorhandler,

We have released a [new version](https://github.com/awslabs/amazon-qldb-driver-go/releases/tag/v1.1.1) of the Go driver that contains this fix.
