### ISSUE TITLE
Remove unused retryLimit variable in session.go

### ISSUE THREAD

**Issue by byronlin-bq** [awslabs/amazon-qldb-driver-go#5]
Currently in session struct there is a retryLimit attribute that is not being used. Lets remove it and in qldbdriver.go

https://github.com/awslabs/amazon-qldb-driver-go/blob/master/qldbdriver/session.go#L27

**Comment by aurghob33** [comment]
The issue was addressed as part of a recent PR. 
Resolving this issue.
Please feel free to reopen if needed.
Thanks Byron!
