### ISSUE TITLE
error inserting time.Time values

### ISSUE THREAD

**Issue by xoba** [awslabs/amazon-qldb-driver-go#51]
on inserting a time.Time value i get the following error: ```ionhash: Invalid operation at hasher.sum: A sum may only be provided at the same depth hashing started```.

code like this reproduces the error:

```
// assumes a table "test" already exists in qldb:
func TimeIssue(driver *qldbdriver.QLDBDriver) error {
	if _, err := driver.Execute(context.Background(), func(txn qldbdriver.Transaction) (interface{}, error) {
		return txn.Execute("INSERT INTO test ?", map[string]interface{}{
			"mytime": time.Now(),
		})
	}); err != nil {
		return err
	}
	return nil
}
```

my go module dependencies are:

```
github.com/awslabs/amazon-qldb-driver-go v1.1.0
github.com/amzn/ion-go v1.1.0
```

note that by replacing a time.Time value with an ion.Timestamp, the error goes away.

**Comment by simonz-bq** [comment]
We'll look into this and get back to you shortly!

**Comment by xoba** [comment]
thanks! forgot to mention `go version go1.16.4 darwin/amd64`.

**Comment by byronlin13** [comment]
Hi @xoba,

We have released a [new version](https://github.com/awslabs/amazon-qldb-driver-go/releases/tag/v1.1.1) of the Go driver that fixes this bug.

Closing the ticket for now, but let us know if you still have the same problem with the new fix.
