### ISSUE TITLE
How to implement paging through a result set

### ISSUE THREAD

**Issue by jabalsad** [awslabs/amazon-qldb-driver-go#61]
Hi,

We'd like to be able to use the pagination features, without having to implement all the logic around committing transactions ourselves. The driver is useful in that it wraps a lot of the underlying `SendCommand` logic, but leaves us with no easy way to implement pagination in our API. I'm thinking along the lines of having some sort of `NextPage()` interface on the `Result` type.

Is this the best way to go about solving this problem? Any advice would be appreciated.

**Comment by alpian** [comment]
Hi @jabalsad, 

Just to be sure I understand, you'd like access to the individual pages of data, rather than the normalized stream of elements we currently provide. I just want to check that you do want to rely on our pagination. What if, at some later point, we change the page size, or maybe eliminate pagination somehow, how would this affect you. I'm not adverse to exposing this, just trying to understand what end result you are hoping to achieve :).

**Comment by alpian** [comment]
We could abstract this internally I supposed and in the initial implementation the pages we expose could be the actual pages, which leaves us open later to fill them artificially if our paging strategy changes. Would that work for you?

**Comment by jabalsad** [comment]
Hi @alpian and thanks for the prompt response.

What I'm getting at is better control over pagination - right now we have none. I would guess that page size is a parameter that is supplied to the execute statement somehow. But I imagine exposing a PagedResult of some kind, with the next page token being accessible on the interface.

**Comment by jabalsad** [comment]
> We could abstract this internally I supposed and in the initial implementation the pages we expose could be the actual pages, which leaves us open later to fill them artificially if our paging strategy changes. Would that work for you?

Yes, I think this also works. If I understand you correctly, you're saying that you will still configure the page size parameters, but expose pages instead of individual results. This makes sense to me, except the execute statement will still require a way to supply the next page token.

**Comment by alpian** [comment]
Are you looking to control the amount of data that comes over the network, or hoping to page results over a long time period, or expecting to show the result in some kind of visual table one page at a time? Just trying to understand what controls you want :).

**Comment by jabalsad** [comment]
Mostly (2/3) - paging over a long period (we're returning the page tokens in our API), and we could be showing results in a paged table of some kind.

**Comment by marcbowes** [comment]
A session is conceptually a connection to the database. Fetching a page requires the next page token (as you call out), but also *the FetchPage must be done on the same session while the transaction is active*. Thus, it's not valid to "return[..] the page tokens in our API" - you would also need to return the session token and transaction ID *and your user would need to redeem future pages before the transaction expires*.

I think it's perfectly fine to extend pagination controls into the driver, but the rest of the usage requirements break semantics. A session is a connection and really should not be "resumed" in subsequent API calls (presumably on a different one of your API hosts). 

@jabalsad I will follow up with you off-camera to better understand your use-case and make sure we're working towards solving it (coloring in within the lines, so to speak).

**Comment by jabalsad** [comment]
> A session is conceptually a connection to the database. Fetching a page requires the next page token (as you call out), but also _the FetchPage must be done on the same session while the transaction is active_. Thus, it's not valid to "return[..] the page tokens in our API" - you would also need to return the session token and transaction ID _and your user would need to redeem future pages before the transaction expires_.

Thanks - I was just made aware of this after learning more about how the raw QLDB API works :-) It does seem like perhaps this is just not a use-case that is currently supported by QLDB (paging across sessions), and likely means we have to reevaluate the priority of building the system that replicates to DDB.

**Comment by marcbowes** [comment]
I'm not sure if there is a clear action item here. Off-camera we discussed doing "internal pagination" until the QLDB services supports richer controls. Such controls would be in Partiql, not the driver.

I'm going to close this, please reopen if there are specific things you'd like us to action.
